Gym_Fitness/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings # Importa settings
from django.conf.urls.static import static # Importa static

# Asegúrate de importar login_view si lo usas directamente aquí
from perfil.views import login_view # Asumiendo que login_view está en perfil/views.py

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_view, name='login'),
    path('perfil/', include('perfil.urls')),
    path('progreso/', include('progreso.urls')),
    path('analisis-postura/', include('nutricion.urls', namespace='analisis_postura')),
]

# ESTAS LÍNEAS SON FUNDAMENTALES PARA SERVIR ARCHIVOS MEDIA EN DESARROLLO
# Y DEBEN ESTAR DENTRO DE LA CONDICIÓN DEBUG
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Perfil/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.login_view, name='logout'),
    path('perfil/', views.perfil, name='perfil'),

]

nutricion/urls.py
from django.urls import path
from . import views

# Cambiamos el nombre de la aplicación para reflejar su nuevo propósito
app_name = 'analisis_postura'

urlpatterns = [
    # Ruta para la página de subida y análisis de video
    path('analizar-video/', views.analizar_video, name='analizar_video'),
    # Puedes añadir otras rutas aquí si las necesitas en el futuro
]

templates/includes/footer-fullscreen.html
<footer class="py-5">
  <div class="container">
    <div class="row align-items-center justify-content-center">
      <div class="col-md-12">
        <div class="copyright text-center text-muted">
           &copy; Created by Group 6
        </div>
      </div>
    </div>
  </div>
</footer>

templates/includes/navigation-fullscreen.html
<nav id="navbar-main" class="navbar navbar-horizontal navbar-transparent navbar-main navbar-expand-lg navbar-light">
  <div class="container">
    <a class="navbar-brand" href="/">
  <img src="/static/assets/img/brand/blue.png" alt="Gym Fitness Logo">
</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse navbar-custom-collapse collapse" id="navbar-collapse">
      <div class="navbar-collapse-header">
        <div class="row">
          <div class="col-6 collapse-brand">
              <a href="/">
                <img src="/static/assets/img/brand/blue.png" alt="Gym Fitness Logo Blue">
              </a>
          </div>
          <div class="col-6 collapse-close">
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
              <span></span>
              <span></span>
            </button>
          </div>
        </div>
      </div>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a href="/" class="nav-link">
            <span class="nav-link-inner--text">Login</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'register' %}" class="nav-link">
            <span class="nav-link-inner--text">Register</span>
  </a>
</li>

      </ul>
      <hr class="d-lg-none" />
      <ul class="navbar-nav align-items-lg-center ml-lg-auto">
        <li class="nav-item">
          <a class="nav-link nav-link-icon" href="https://www.facebook.com"
             target="_blank" data-toggle="tooltip" data-original-title="Like us on Facebook">
            <i class="fab fa-facebook-square"></i>
            <span class="nav-link-inner--text d-lg-none">Facebook</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-link-icon" href="https://www.instagram.com"
             target="_blank" data-toggle="tooltip" data-original-title="Follow us on Twitter">
            <i class="fab fa-twitter-square"></i>
            <span class="nav-link-inner--text d-lg-none">Instagram</span>
          </a>
        </li>

      </ul>
    </div>
  </div>
</nav>

templates/includes/navigation.html
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Search form (se mantiene si lo necesitas) -->

      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center  ml-md-auto ">
        <li class="nav-item d-xl-none">
          <!-- Sidenav toggler -->
          <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </div>
        </li>
        <li class="nav-item d-sm-none">
          <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
            <i class="ni ni-zoom-split-in"></i>
          </a>
        </li>
        {# SECCIONES ELIMINADAS: Campana de notificaciones y el cuadro de accesos directos #}
        {# <li class="nav-item dropdown"> ... </li> para la campana de notificaciones #}
        {# <li class="nav-item dropdown"> ... </li> para el cuadro de accesos directos #}
      </ul>
      <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
        <li class="nav-item dropdown">
          <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="media align-items-center">
                <span class="avatar avatar-sm rounded-circle">
                  {% if request.user.foto_perfil %}
                    <img alt="Foto de Perfil" src="{{ request.user.foto_perfil.url }}">
                  {% else %}
                    <img alt="Imagen de Perfil por defecto" src="/static/assets/img/theme/team-4.jpg">
                  {% endif %}
                </span>
                <div class="media-body  ml-2  d-none d-lg-block">
                  <span class="mb-0 text-sm  font-weight-bold">
                    {{ request.user.username }}
                  </span>
                </div>
              </div>
            </a>
          <div class="dropdown-menu  dropdown-menu-right ">
            <div class="dropdown-header noti-title">
              <h6 class="text-overflow m-0">Welcome!</h6>
            </div>
            <a href="{% url 'perfil' %}" class="dropdown-item">
              <i class="ni ni-single-02"></i>
              <span>Mi Perfil</span>
            </a>

            <div class="dropdown-divider"></div>
            <a href="{% url 'login' %}" class="dropdown-item">
              <i class="ni ni-user-run text-red"></i>
              <span>Logout</span>
            </a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/includes/scripts.html
  <script src="/static/assets/vendor/jquery/dist/jquery.min.js"></script>
  <script src="/static/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="/static/assets/vendor/js-cookie/js.cookie.js"></script>
  <script src="/static/assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
  <script src="/static/assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js"></script>

templates/includes/sidenav.html
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
  <div class="scrollbar-inner">
    <!-- Brand -->
    <div class="sidenav-header  align-items-center">
      <a class="navbar-brand" href="/">
        <img src="/static/assets/img/brand/blue.png" class="navbar-brand-img" alt="Argon Design - Jinja Template Logo." style="width: 180px; height: 180px;">
      </a>
    </div>
    <div class="navbar-inner">
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Nav items -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link {% if 'dashboard' in segment %} active {% endif %}" href="{% url 'dashboard' %}">
              <i class="ni ni-tv-2 text-primary" style="font-size: 1.5rem; margin-right: 0.3rem;"></i>
              <span class="nav-link-text" style="font-size: 1.4rem;">Dashboard</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'perfil' %}">
              <i class="ni ni-single-02 text-yellow" style="font-size: 1.5rem; margin-right: 0.3rem;"></i>
              <span class="nav-link-text" style="font-size: 1.4rem;">Perfil</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if 'profile' in segment %} active {% endif %}" href="/progreso">
              <i class="ni ni-chart-bar-32 text-red" style="font-size: 1.5rem; margin-right: 0.3rem;"></i>
              <span class="nav-link-text" style="font-size: 1.4rem;">Progreso</span>
            </a>
          </li>
          <li class="nav-item">
  {# Actualiza el href con la URL correcta para tu vista de análisis de video #}
  <a class="nav-link {% if 'analisis_postura' in segment %} active {% endif %}" href="{% url 'analisis_postura:analizar_video' %}">
    <i class="fas fa-video" style="font-size: 1.5rem; margin-right: 0.3rem; color: #8FBC8F;"></i> {# Cambié el icono a video #}
    <span class="nav-link-text" style="font-size: 1.4rem;">Análisis de Postura</span> {# Cambié el texto #}
  </a>
</li>

        </ul>
        <!-- Divider -->
        <hr class="my-3">
        <!-- Heading -->


            <a class="dropdown-item" href="{% url 'logout' %}">
              <i class="ni ni-user-run text-dark" style="font-size: 1.5rem; margin-right: 0.3rem;"></i>
              <span class="nav-link-text" style="font-size: 1.4rem;">Logout</span>
            </a>


      </div>
    </div>
  </div>
</nav>